### ISSUE TITLE
unknown plugin option navigateFallbackWhitelist

### ISSUE THREAD

**Issue by derykmarl** [jon-sully/gatsby-plugin-force-trailing-slashes#14]
Per the readme, because we're using gatsby-plugin-offline we are supposed to have this:

```
{
    resolve: 'gatsby-plugin-offline',
    options: {
        navigateFallbackWhitelist: [/\/$/],
    }
}
```

However this results in the message "Warning: there are unknown plugin options for "gatsby-plugin-offline": navigateFallbackWhitelist
Please open an issue at ghub.io/gatsby-plugin-offline if you believe this option is valid."

(I haven't actually opened an issue there as I'm not sure if this is more a documentation issue here)

Since the upgrade to Gatsby v3, I believe it would now need to be structured as follows, but this doesn't work either (same warning):

```
    {
      resolve: `gatsby-plugin-offline`,
      options: {
        workboxConfig: {
          navigateFallbackWhitelist: [/\/$/],
        }
      }
    },
```

Per the latest version of workbox I have also tried changing both formats to say navigateFallback**Allow**list but again, same message.

Is this option particularly important?

**Comment by jon-sully** [comment]
Hey there 👋🏻 did you mean to post this in this plugin's repo? This repository is for the forced-trailing-slashes plugin 👀

**Comment by derykmarl** [comment]
I did as I'm referring to your documentation here (troubleshooting section) which is resulting in the warnings mentioned:

https://www.gatsbyjs.com/plugins/gatsby-plugin-force-trailing-slashes/

**Comment by jon-sully** [comment]
Ah! My apologies. I recently became the primary maintainer of this plugin and hadn't versed myself on that part yet.

My guess here would be that the `navigateFallbackWhitelist` key changed somewhere in the offline plugin's development. I can't exactly tell if that key ever existed in prior versions and I can't figure out what that option would do anyway.

I'd say if you're following the 3 steps outlined at the top of this plugin's documentation, go ahead and skip the `navigateFallbackWhitelist` stuff. Given what _this_ plugin does and how it interacts with Gatsby, I don't actually think there's likely any interaction with it and Workbox. I'd say try it out, test it thoroughly, and feel free to report back if something isn't working. I'd be happy to check it out if something is actively appearing to be broken.

**Comment by derykmarl** [comment]
Alright that makes sense, I'll just leave it out then!  Thanks for your advice

**Comment by jon-sully** [comment]
Closing this issue in line with the deprecation of this package coming in the future and Gatsby's addition of trailing slash support natively (as of 4.7, please see https://github.com/gatsbyjs/gatsby/discussions/34205)
