### ISSUE TITLE
Not working for Netlify

### ISSUE THREAD

**Issue by max8hine** [jon-sully/gatsby-plugin-force-trailing-slashes#3]
Hi, I tried this plugin, It works perfectly in local development mode but not on the server of Netlify.

How does this plugin work? Thanks.

**Comment by max8hine** [comment]
Oh, I found the reason, the offline plugin causing the issue. 

below setting will be fixed.
```
{
    resolve: 'gatsby-plugin-offline',
    options: {
        navigateFallbackWhitelist: [/\/$/],
    }
}
```

**Comment by BayPhillips** [comment]
Oh wow, nice find @max8hine ! That sounds like a good thing to throw into the README for folks in the future?

**Comment by max8hine** [comment]
Sorry for the delayed response, @BayPhillips.
Yes, I think it should be good throw into the README for folks who use Gatsby.js V2

**Comment by Dakuan** [comment]
this still isn't working for me, is it order dependent?

**Comment by obedparla** [comment]
This fixed my issue, thanks @max8hine ! I made sure I had this plugin _after_ the offline plugin one @Dakuan

**Comment by jon-sully** [comment]
Closing this issue in line with the deprecation of this package coming in the future and Gatsby's addition of trailing slash support natively (as of 4.7, please see https://github.com/gatsbyjs/gatsby/discussions/34205)
