### ISSUE TITLE
Doesn't work with Gatsby's <Link> component

### ISSUE THREAD

**Issue by thomasryu** [jon-sully/gatsby-plugin-force-trailing-slashes#4]
Using Gatsby's [Link](https://www.gatsbyjs.org/docs/gatsby-link/) component still takes you to a subdomain without a trailing slash.

(e.g. `<Link to='about'>` takes me to `mydomain.com/about` and not `mydomain.com/about/`. Using `<Link to='about/'>` works but defeats the purpose of the plugin in this case)

**Comment by jon-sully** [comment]
This plugin essentially exists to convert `./public/foo.html` into `./public/foo/index.html` as to adhere to the historical specification of the internet treating directories as paths _with_ trailing slashes and documents as paths _without_ trailing slashes (where `foo.html` alone is a _document_ and `foo/index.html` is a _directory_). The plugin does the job perfectly well! 

It's up to you (and me!) to write our markup with knowledge of what this plugin is doing and to write our Anchor tags and `<Link>`s to _target_ the trailing-slash version of any given path. This plugin isn't made to parse through all your (and my) markup, sniff out internal `<Link>`s and change their `to=` field.

_We_ pulled down and installed this plugin. _We_ should know that when we write `<Link to="/blog">`, we should instead make it `<Link to="/blog/">`

Hope that helps :)

**Comment by jon-sully** [comment]
Howdy 👋🏻

I'm not sure if you're still around / using this plugin / etc but I wanted to leave a comment here for others who come in the future (although I did update the project README so it better clarifies what's needed to get Gatsby unified on trailing slashes) — this plugin ultimately aims to correctly configure the `@reach/router` under the hood during the Gatsby build-time process where the router is pre-programmed before it gets hydrated client-side. 

That's a really important step for unifying a Gatsby site to use trailing slashes, but it's not the only step. As of right now, unfortunately the third part of that equation _is_ to ensure that all uses of Gatsby's `<Link>` component (and any uses of `navigate()`) specify a trailing-slash `to=` target. This is just a side-effect of the decision made for the `@reach/router` to [not care about trailing slashes](https://reach.tech/router/nesting) — so when the PWA navigation runs, the router won't care whether or not it has a trailing slash and will put the string we wrote in the `<Link>` directly in the address bar. 

I wrote about this with a lot of depth and solution(s) in the Gatsby discussion board: https://github.com/gatsbyjs/gatsby/discussions/27889

---


In the future I may wrap Gatsby's `<Link>` with one that injects the trailing slash for us, but then we'd need to change all of our `import { Link } from 'gatsby'` lines to import from this plugin instead. Not horrible, but not awesome either. I'd prefer to find a way to monkey-patch `<Link>` from this plugin. TBD.

**Comment by epbarger** [comment]
@jon-sully I too am having an issue with the `<Link>` component. Like you mentioned above, I'm wrapping `<Link>` in a component that enforces the trailing backslash is part of the url. However, this doesn't seem to work with urls that use folder navigation. For example `../example_b/` on the page `/examples/example_a/`, will produce the link `/examples/example_b`. To me, this suggests `@reach/router` is stripping the trailing backslash when producing the final link. Have you seen this happen, or am I doing something incorrectly?

**Comment by jon-sully** [comment]
Hey @epbarger! Actually yeah, I did play around with `<Link>` quite a bit recently (especially in building client-side-only paths) and found similar — you can't use relative pathing. You have to use root pathing. So not `"../example_b/"` but `"/examples/example_b/"`. And indeed, this is the router's ambivalence toward trailing slashes. Not my favorite but it is what it is.

**Comment by epbarger** [comment]
Good to know it's not just me, thanks for the response!

**Comment by jon-sully** [comment]
Closing this issue in line with the deprecation of this package coming in the future and Gatsby's addition of trailing slash support natively (as of 4.7, please see https://github.com/gatsbyjs/gatsby/discussions/34205)
