### ISSUE TITLE
Non-trailing slash URLs duplicate content - redirection on Netlify?

### ISSUE THREAD

**Issue by i-bsd** [jon-sully/gatsby-plugin-force-trailing-slashes#7]
This plugin creates trailing slash URLs just fine but the non-trailing slash URLs are still there. So basically there's a duplicate of every page.

Is there a way to prevent this?

**Comment by iloveip** [comment]
Hi @i-bsd,

Did you find a way to fix this problem (with duplicating pages)?

**Comment by jon-sully** [comment]
Hey there! This may help:

https://jonsully.net/blog/trailing-slashes-on-netlify/

**Comment by DanielRiveraHQ** [comment]
But, is there any way to do this within Gatsby Cloud?

**Comment by jon-sully** [comment]
Hey @DanielRiveraHQ 👋 

Unfortunately I can't say — I'm personally unfamiliar with Gatsby Cloud's server-level / routing controls.

**Comment by jon-sully** [comment]
Closing this issue in line with the deprecation of this package coming in the future and Gatsby's addition of trailing slash support natively (as of 4.7, please see https://github.com/gatsbyjs/gatsby/discussions/34205)
